"""
core/audio_manifest.py - Parse NGPC Sound Creator project_audio_manifest.txt

The manifest is generated by NGPC Sound Creator (Project Export All) and looks like:

    Generated by NGPC Sound Creator - Project Audio Manifest
    mode=C
    song_count=2
    songs:
      - id=stage1 | name=Stage 1 | file=exports/stage1.c | symbols=PROJECT_STAGE1_*
      - id=boss   | name=Boss    | file=exports/boss.c   | symbols=PROJECT_BOSS_*
    instruments=exports/project_instruments.c
    sfx=exports/project_sfx.c
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AudioSong:
    """One song entry parsed from a Sound Creator audio manifest."""

    idx: int
    song_id: str
    name: str
    file: str
    symbols: str


@dataclass(frozen=True)
class AudioManifest:
    """Normalized representation of `project_audio_manifest.txt`."""

    mode: str
    songs: list[AudioSong]
    instruments: str | None
    sfx: str | None


def parse_audio_manifest_text(text: str) -> AudioManifest:
    """Parse Sound Creator manifest text into an `AudioManifest` object."""
    mode = ""
    instruments = None
    sfx = None
    songs: list[AudioSong] = []

    in_songs = False
    for raw in (text or "").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("mode="):
            mode = line.split("=", 1)[1].strip()
            continue
        if line == "songs:":
            in_songs = True
            continue
        if in_songs:
            if not line.startswith("- "):
                in_songs = False
            else:
                payload = line[2:].strip()
                parts = [p.strip() for p in payload.split("|")]
                kv: dict[str, str] = {}
                for p in parts:
                    if "=" in p:
                        k, v = p.split("=", 1)
                        kv[k.strip()] = v.strip()
                songs.append(
                    AudioSong(
                        idx=len(songs),
                        song_id=kv.get("id", ""),
                        name=kv.get("name", kv.get("id", "")),
                        file=kv.get("file", ""),
                        symbols=kv.get("symbols", ""),
                    )
                )
                continue

        if line.startswith("instruments="):
            instruments = line.split("=", 1)[1].strip()
        elif line.startswith("sfx="):
            sfx = line.split("=", 1)[1].strip()

    return AudioManifest(mode=mode, songs=songs, instruments=instruments, sfx=sfx)


def load_audio_manifest(path: Path) -> AudioManifest:
    """Load and parse a Sound Creator manifest from disk."""
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    return parse_audio_manifest_text(text)


def resolve_manifest_asset_path(manifest_dir: "Path | None", rel_path: str) -> "Path | None":
    """Resolve a manifest-referenced file against common Sound Creator layouts."""
    if manifest_dir is None:
        return None
    rel = str(rel_path or "").strip()
    if not rel:
        return None

    raw = Path(rel)
    candidates: list[Path] = []
    if raw.is_absolute():
        candidates.append(raw)
    else:
        base = Path(manifest_dir)
        candidates.append(base / raw)
        candidates.append(base.parent / raw)
        if raw.name:
            candidates.append(base / raw.name)
            candidates.append(base.parent / raw.name)

    seen: set[str] = set()
    for p in candidates:
        key = str(p).lower()
        if key in seen:
            continue
        seen.add(key)
        if p.exists():
            return p
    return None


def parse_sfx_names_from_c(text: str) -> list[tuple[int, str]]:
    """Parse SFX index/name pairs from a Sound Creator project_sfx.c file."""
    import re

    results: list[tuple[int, str]] = []
    for line in (text or "").splitlines():
        m = re.match(r"/\*\s*(\d+)\s*:\s*(.+?)\s*\*/", line.strip())
        if m:
            results.append((int(m.group(1)), m.group(2)))
    results.sort(key=lambda t: t[0])
    return results


def parse_sfx_count_from_c(text: str) -> int | None:
    """Parse the `PROJECT_SFX_COUNT` literal from a Sound Creator SFX bank."""
    import re

    m = re.search(r"\bPROJECT_SFX_COUNT\b\s*=\s*(\d+)\s*(?:u|U)?\s*;", text or "")
    if not m:
        return None
    try:
        return int(m.group(1))
    except Exception:
        return None


def load_sfx_count(manifest: "AudioManifest | None", manifest_dir: "Path | None") -> int | None:
    """Load the SFX bank count from the manifest-referenced `project_sfx.c` file."""
    if manifest is None or not manifest.sfx or manifest_dir is None:
        return None
    sfx_path = resolve_manifest_asset_path(manifest_dir, manifest.sfx)
    if sfx_path is None:
        return None
    try:
        text = sfx_path.read_text(encoding="utf-8", errors="replace")
        return parse_sfx_count_from_c(text)
    except Exception:
        return None


def load_sfx_names(manifest: "AudioManifest | None", manifest_dir: "Path | None") -> list[tuple[int, str]]:
    """Load SFX (index, name) pairs from the sfx file referenced in *manifest*."""
    if manifest is None or not manifest.sfx or manifest_dir is None:
        return []
    sfx_path = resolve_manifest_asset_path(manifest_dir, manifest.sfx)
    if sfx_path is None:
        return []
    try:
        text = sfx_path.read_text(encoding="utf-8", errors="replace")
        return parse_sfx_names_from_c(text)
    except Exception:
        return []
