"""
core/audio_autogen_mk.py - Generate a Makefile include listing Sound Creator exports.

Goal (AUD-4): avoid manually adding Sound Creator exports (*.c) to OBJS.

We write an include file (audio_autogen.mk) that appends .rel objects for the
audio files that must be compiled standalone.
"""

from __future__ import annotations

from pathlib import Path

from core.audio_manifest import resolve_manifest_asset_path


def project_uses_template_managed_audio(project_dir: Path) -> bool:
    """Return True when hybrid exports are already aggregated by `sound_data.c`."""
    project_dir = Path(project_dir)
    sound_data = project_dir / "sound" / "sound_data.c"
    sound_new = project_dir / "sound" / "new"
    return sound_data.is_file() and sound_new.is_dir() and any(sound_new.glob("*.c"))


def write_disabled_audio_autogen_mk(out_dir: Path, reason: str | None = None) -> Path:
    """Write a harmless audio_autogen.mk when standalone audio objects must stay disabled."""
    out_dir = Path(out_dir)
    mk_path = out_dir / "audio_autogen.mk"
    lines = [
        "# Auto-generated by NgpCraft Engine -- do not edit\n",
        "# Standalone audio objects intentionally disabled.\n",
    ]
    if reason:
        lines.append(f"# Reason: {reason}\n")
    lines.append("# sound/sound_data.c already aggregates the active hybrid exports.\n")
    out_dir.mkdir(parents=True, exist_ok=True)
    mk_path.write_text("".join(lines), encoding="utf-8")
    return mk_path


def write_audio_autogen_mk(project_dir: Path, exports_dir: Path, out_dir: Path | None = None, manifest=None) -> Path:
    """
    Generate:
      (out_dir or exports_dir)/audio_autogen.mk

    Each entry becomes:
      OBJS += $(OBJ_DIR)/<relpath>.rel
    where relpath is relative to project_dir.
    """
    project_dir = Path(project_dir)
    exports_dir = Path(exports_dir)
    out_dir = Path(out_dir) if out_dir is not None else exports_dir
    mk_path = out_dir / "audio_autogen.mk"

    c_files: list[Path] = []
    if manifest is not None:
        for song in getattr(manifest, "songs", []) or []:
            song_path = resolve_manifest_asset_path(exports_dir, getattr(song, "file", ""))
            if song_path is not None and song_path.suffix.lower() == ".c":
                c_files.append(song_path)
        sfx_rel = str(getattr(manifest, "sfx", "") or "").strip()
        if sfx_rel:
            sfx_path = resolve_manifest_asset_path(exports_dir, sfx_rel)
            if sfx_path is not None and sfx_path.suffix.lower() == ".c":
                c_files.append(sfx_path)
        sfx_autogen = exports_dir / "sounds_game_sfx_autogen.c"
        if sfx_autogen.is_file():
            c_files.append(sfx_autogen)

    if not c_files and exports_dir.exists():
        for p in exports_dir.rglob("*.c"):
            n = p.name.lower()
            if n == "audio_autogen.c":
                continue
            if n.endswith("_instruments.c"):
                continue
            if n == "sound_data.c":
                continue
            if n == "project_audio_api.c":
                continue
            c_files.append(p)

    rel_objs: list[str] = []
    skipped_outside: list[Path] = []
    seen_files: set[str] = set()
    for c in sorted(c_files):
        key = str(c).lower()
        if key in seen_files:
            continue
        seen_files.add(key)
        try:
            rel = c.relative_to(project_dir)
        except ValueError:
            skipped_outside.append(c)
            continue
        rel_rel = str(rel).replace("\\", "/")
        if rel_rel.lower().endswith(".c"):
            rel_rel = rel_rel[:-2] + ".rel"
        rel_objs.append(f"$(OBJ_DIR)/{rel_rel}")

    lines: list[str] = []
    lines.append("# Auto-generated by NgpCraft Engine -- do not edit\n")
    lines.append("# Generated objects from Sound Creator exports (.c -> .rel)\n")
    lines.append("# Tip: include this file in your makefile when NGP_ENABLE_SOUND=1\n\n")

    if rel_objs:
        lines.append("ifneq ($(strip $(NGP_ENABLE_SOUND)),0)\n")
        lines.append("CDEFS += -Isrc/audio\n")
        if any(p.name.lower() == "sounds_game_sfx_autogen.c" for p in c_files):
            lines.append("CDEFS += -DSFX_PLAY_EXTERNAL=1\n\n")
        for obj in rel_objs:
            lines.append(f"OBJS += {obj}\n")
        lines.append("endif\n")
    else:
        lines.append("# (no standalone .c exports found)\n")

    if skipped_outside:
        lines.append("# WARN: some export files are outside project_dir and were skipped:\n")
        for p in skipped_outside[:20]:
            lines.append(f"#   - {p}\n")
        if len(skipped_outside) > 20:
            lines.append(f"#   ... ({len(skipped_outside) - 20} more)\n")
        lines.append("\n")

    out_dir.mkdir(parents=True, exist_ok=True)
    mk_path.write_text("".join(lines), encoding="utf-8")
    return mk_path
