"""
core/entity_types_gen.py — Generate ngpc_entity_types.h from project entity_types.

Tree-shaking: only emits types that are actually referenced by at least one entity
instance (or wave entity) across all scenes. Types defined in Globals but never
placed in any scene produce zero C output.

Runtime cost:
  - All data is const (ROM), zero RAM.
  - Lookup is O(1) by EntityTypeId enum index.
  - Array only contains used types — no padding, no dead entries.

Project data format (in .ngpcraft):
    {
        "entity_types": [
            {
                "id": "etype_slime",
                "name": "slime",
                "role": "enemy",
                "behavior": 0,        # 0=Patrol 1=Chase 2=Fixed 3=Random
                "ai_speed": 1,
                "ai_range": 10,
                "ai_lose_range": 16,
                "ai_change_every": 60,
                "direction": 0,
                "data": 0,
                "flags": 0
            }
        ],
        "scenes": [
            {
                "entities": [{"type_id": "etype_slime", ...}],
                "waves": [{"entities": [{"type_id": "etype_slime", ...}]}]
            }
        ]
    }

Generated output (ngpc_entity_types.h):
    #ifndef NGPC_ENTITY_TYPES_GEN_H
    #define NGPC_ENTITY_TYPES_GEN_H
    typedef enum { ET_SLIME = 0 } EntityTypeId;
    typedef struct { u8 role; u8 behavior; u8 speed; u8 range; u8 lose_range; u8 change_every; u8 dir; u8 data; u8 flags; } EntityTypeDef;
    static const EntityTypeDef et_table[] = { ... };
    #define ET_TABLE_SIZE  1
    #endif

Usage:
    from core.entity_types_gen import write_entity_types_h, collect_used_type_ids
    path = write_entity_types_h(project_data=data, export_dir=Path("GraphX/gen"))
"""
from __future__ import annotations

import re
from pathlib import Path

from core.entity_types import get_entity_types, ROLE_VALUES
from core.entity_templates import get_entity_templates

_OUTPUT_FILENAME = "ngpc_entity_types.h"
_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Maps role string → u8 value for C output
_ROLE_TO_INT: dict[str, int] = {r: i for i, r in enumerate(ROLE_VALUES)}


def _enum_name(type_name: str) -> str:
    """Convert type name to upper-case enum constant (e.g. 'big_slime' → 'ET_BIG_SLIME')."""
    safe = re.sub(r"[^A-Za-z0-9_]", "_", str(type_name or "")).strip("_").upper()
    if not safe or not _IDENT_RE.match(safe):
        safe = "TYPE"
    return f"ET_{safe}"


def collect_used_type_ids(project_data: dict) -> set[str]:
    """Return the set of entity type IDs referenced by any entity instance in any scene."""
    used: set[str] = set()
    if not isinstance(project_data, dict):
        return used
    for scene in project_data.get("scenes", []) or []:
        if not isinstance(scene, dict):
            continue
        # Static entity placements
        for ent in scene.get("entities", []) or []:
            if isinstance(ent, dict) and ent.get("type_id"):
                used.add(str(ent["type_id"]))
        # Wave spawn entities
        for wave in scene.get("waves", []) or []:
            if not isinstance(wave, dict):
                continue
            for ent in wave.get("entities", []) or []:
                if isinstance(ent, dict) and ent.get("type_id"):
                    used.add(str(ent["type_id"]))
    return used


def make_entity_types_h(*, project_data: dict) -> str:
    """Return the full content of ngpc_entity_types.h as a string.

    If no entity types are referenced, returns a minimal header with no data.
    """
    # Merge: entity_templates[] (full prefabs) take priority, then legacy entity_types[]
    # Dedup by id — first occurrence wins (templates are listed first)
    seen_ids: set[str] = set()
    all_types: list[dict] = []
    for t in get_entity_templates(project_data) + get_entity_types(project_data):
        if isinstance(t, dict) and t.get("id") and t["id"] not in seen_ids:
            seen_ids.add(t["id"])
            all_types.append(t)

    used_ids = collect_used_type_ids(project_data)

    # Filter to only used types, preserving declaration order
    active = [t for t in all_types if t.get("id") in used_ids]

    lines: list[str] = [
        "/* ngpc_entity_types.h — auto-generated by NgpCraft Engine */",
        "/* DO NOT EDIT — re-export from the project tab to update.  */",
        "#ifndef NGPC_ENTITY_TYPES_GEN_H",
        "#define NGPC_ENTITY_TYPES_GEN_H",
        "",
    ]

    if not active:
        lines += [
            "/* (no entity types referenced in any scene) */",
            "",
            "#endif /* NGPC_ENTITY_TYPES_GEN_H */",
            "",
        ]
        return "\n".join(lines)

    # Build enum — one constant per active type, values 0..N-1
    enum_names = [_enum_name(t.get("name", t.get("id", f"type_{i}"))) for i, t in enumerate(active)]
    max_ename = max(len(n) for n in enum_names)

    enum_members = []
    for i, (t, ename) in enumerate(zip(active, enum_names)):
        pad = " " * (max_ename - len(ename))
        sep = "," if i < len(active) - 1 else ""
        enum_members.append(f"    {ename}{pad} = {i}{sep}   /* {t.get('id', '')} */")

    lines += [
        "typedef enum {",
        *enum_members,
        "} EntityTypeId;",
        "",
        "typedef struct {",
        "    u8 role;",
        "    u8 behavior;",
        "    u8 speed;",
        "    u8 range;",
        "    u8 lose_range;",
        "    u8 change_every;",
        "    u8 dir;",
        "    u8 data;",
        "    u8 flags;",
        "} EntityTypeDef;",
        "",
        "static const EntityTypeDef et_table[] = {",
    ]

    for i, (t, ename) in enumerate(zip(active, enum_names)):
        role_int  = _ROLE_TO_INT.get(str(t.get("role", "enemy")), 0)
        behavior  = int(t.get("behavior", 0))
        speed     = int(t.get("ai_speed", 1))
        rng       = int(t.get("ai_range", 10))
        lose      = int(t.get("ai_lose_range", 16))
        change_ev = int(t.get("ai_change_every", 60))
        direction = int(t.get("direction", 0))
        data      = int(t.get("data", 0))
        flags     = int(t.get("flags", 0))
        sep = "," if i < len(active) - 1 else ""
        lines.append(
            f"    /* {ename} */ "
            f"{{ {role_int}, {behavior}, {speed}, {rng}, {lose}, {change_ev}, {direction}, {data}, {flags} }}{sep}"
        )

    lines += [
        "};",
        "",
        f"#define ET_TABLE_SIZE  {len(active)}",
        "",
        "#endif /* NGPC_ENTITY_TYPES_GEN_H */",
        "",
    ]
    return "\n".join(lines)


def write_entity_types_h(*, project_data: dict, export_dir: Path) -> Path:
    """Write ``ngpc_entity_types.h`` to *export_dir*. Returns the written path."""
    export_dir = Path(export_dir)
    export_dir.mkdir(parents=True, exist_ok=True)
    content = make_entity_types_h(project_data=project_data)
    out = export_dir / _OUTPUT_FILENAME
    out.write_text(content, encoding="utf-8")
    return out
