"""
core/game_constants_gen.py - Generate ngpc_project_constants.h from project constants list.

Project data format (in .ngpcraft):
    {
        "constants": [
            {"name": "PLAYER_HP_MAX", "value": 3, "comment": "Player starting lives"},
            {"name": "BULLET_SPEED",  "value": 2, "comment": "Bullet speed px/frame"}
        ]
    }

Generated output (ngpc_project_constants.h):
    #ifndef NGPC_PROJECT_CONSTANTS_H
    #define NGPC_PROJECT_CONSTANTS_H
    #define PLAYER_HP_MAX  3   /* Player starting lives */
    #define BULLET_SPEED   2   /* Bullet speed px/frame */
    #endif

Usage:
    from core.game_constants_gen import write_constants_h
    path = write_constants_h(project_data=data, export_dir=Path("GraphX"))
"""
from __future__ import annotations

import re
from pathlib import Path

_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_OUTPUT_FILENAME = "ngpc_project_constants.h"


def _valid_name(name: str) -> bool:
    """Return True if *name* is a valid C identifier."""
    return bool(name) and bool(_IDENT_RE.match(name))


def _clean_rows(project_data: dict) -> list[dict]:
    """Return valid constant rows from project data, skipping malformed entries."""
    rows = project_data.get("constants", []) if isinstance(project_data, dict) else []
    if not isinstance(rows, list):
        return []
    out = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        name = str(row.get("name") or "").strip()
        if not _valid_name(name):
            continue
        out.append({
            "name": name,
            "value": int(row.get("value", 0) if str(row.get("value", "")).lstrip("-").isdigit() else 0),
            "comment": str(row.get("comment") or "").strip(),
        })
    return out


def make_constants_h(*, project_data: dict, guard: str | None = None) -> str:
    """Return the full content of ngpc_project_constants.h as a string.

    Args:
        project_data: The .ngpcraft project dict. Must contain a ``"constants"`` list.
        guard: Optional C include-guard symbol. Defaults to ``NGPC_PROJECT_CONSTANTS_H``.

    Returns:
        C header string, or a minimal header with just the guard if no valid constants.
    """
    rows = _clean_rows(project_data)
    guard = guard or "NGPC_PROJECT_CONSTANTS_H"

    lines: list[str] = [
        "/* ngpc_project_constants.h — auto-generated by NGPC PNG Manager */",
        "/* DO NOT EDIT — re-export from the project tab to update.       */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]

    if rows:
        # Align #define values for readability
        max_name_len = max(len(r["name"]) for r in rows)
        for row in rows:
            name = row["name"]
            value = row["value"]
            comment = row["comment"]
            pad = " " * (max_name_len - len(name) + 2)
            line = f"#define {name}{pad}{value}"
            if comment:
                line += f"   /* {comment} */"
            lines.append(line)
    else:
        lines.append("/* No constants defined — add them in the PNG Manager project tab. */")

    lines += ["", f"#endif /* {guard} */", ""]
    return "\n".join(lines)


def write_constants_h(
    *,
    project_data: dict,
    export_dir: Path,
    guard: str | None = None,
) -> Path:
    """Write ``ngpc_project_constants.h`` to *export_dir*.

    Args:
        project_data: The .ngpcraft project dict.
        export_dir: Directory where the file should be written.
        guard: Optional C include-guard symbol.

    Returns:
        Absolute path to the written file.
    """
    export_dir = Path(export_dir)
    export_dir.mkdir(parents=True, exist_ok=True)
    content = make_constants_h(project_data=project_data, guard=guard)
    out = export_dir / _OUTPUT_FILENAME
    out.write_text(content, encoding="utf-8")
    return out
