"""
core/gen_manifest.py — Track files produced by the headless export pipeline
so orphan generated assets (left over from deleted/renamed sprites, tilemaps,
or scenes) can be safely removed between runs.

Why this exists
---------------
`assets_autogen.mk` builds OBJS by globbing every ``.c`` under the gen
directory. Without a cleanup step, files generated by a previous export
(for assets the user has since removed) keep being linked into the ROM,
producing ghost entities, stale tile data, and ROM bloat.

A naive ``rm GraphX/gen/*`` is unsafe: users sometimes place files there by
hand (custom font sources, etc.), and a mid-export crash would wipe their
work. This module instead persists the exact set of paths each successful
export produced. The next export only removes files that *this* engine
wrote previously and did not regenerate.

Manifest file
-------------
``<gen_dir>/.ngpcraft_gen_manifest.json`` with the shape::

    {
        "version": 1,
        "generated_at": "2026-05-15T12:34:56Z",
        "files": ["player_mspr.c", "scene_level1_level.h", ...]
    }

Paths are stored relative to ``gen_dir`` with POSIX separators. Only files
whose suffix is in :data:`TRACKED_SUFFIXES` are ever recorded or removed —
this is a hard guarantee enforced both at write time and at delete time.
"""

from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path
from typing import Iterable

__all__ = [
    "MANIFEST_NAME",
    "MANIFEST_VERSION",
    "TRACKED_SUFFIXES",
    "GenManifest",
]


MANIFEST_NAME = ".ngpcraft_gen_manifest.json"
MANIFEST_VERSION = 1

# Suffixes the manifest is allowed to track and remove. Anything else under
# gen_dir (PNGs, JSON sidecars, user-placed assets, subdirectories) is never
# touched — even if it somehow ends up in the manifest.
TRACKED_SUFFIXES: frozenset[str] = frozenset({".c", ".h", ".mk", ".inc"})


class GenManifest:
    """Track generated files for one export run.

    Typical usage::

        m = GenManifest(gen_dir)
        m.add(some_path)           # after each successful write
        ...
        if export_ok:
            removed = m.remove_orphans()  # only deletes if the run succeeded
        m.write()                   # persist for next run

    A ``GenManifest`` constructed with ``gen_dir=None`` is inert: every
    method is a no-op and ``remove_orphans()`` returns an empty list. This
    lets callers wire the manifest without conditionals.
    """

    def __init__(self, gen_dir: "Path | str | None"):
        if gen_dir is None:
            self._gen_dir: Path | None = None
        else:
            try:
                self._gen_dir = Path(gen_dir).resolve()
            except Exception:
                self._gen_dir = None
        self._produced: set[str] = set()
        self._previous: set[str] = self._load_previous()

    # ------------------------------------------------------------------
    # public API
    # ------------------------------------------------------------------

    @property
    def gen_dir(self) -> "Path | None":
        return self._gen_dir

    @property
    def manifest_path(self) -> "Path | None":
        return (self._gen_dir / MANIFEST_NAME) if self._gen_dir else None

    @property
    def previous_count(self) -> int:
        return len(self._previous)

    @property
    def produced_count(self) -> int:
        return len(self._produced)

    def add(self, path: "Path | str | None") -> None:
        """Record one generated file. Silently ignored if outside gen_dir
        or if the suffix is not in :data:`TRACKED_SUFFIXES`.
        """
        rel = self._rel(path)
        if rel is not None:
            self._produced.add(rel)

    def add_many(self, paths: Iterable["Path | str | None"]) -> None:
        for p in paths or ():
            self.add(p)

    def remove_orphans(self) -> list[Path]:
        """Delete files that were in the previous manifest but were not
        produced this run. Returns the list of paths actually removed.

        Safety rails (defence in depth):
          * ``gen_dir`` must exist and be a directory.
          * Each path must resolve under ``gen_dir`` (no traversal).
          * Each path's suffix must be in :data:`TRACKED_SUFFIXES`.
          * The manifest file itself is never removed.
          * Symlinks and directories are skipped.
          * Any unlink exception is swallowed (best-effort cleanup must
            not break the export).
        """
        removed: list[Path] = []
        if not self._gen_dir or not self._gen_dir.is_dir():
            return removed
        orphans = self._previous - self._produced
        for rel in sorted(orphans):
            target = self._gen_dir / rel
            if not self._is_safe_to_remove(target):
                continue
            try:
                if target.is_file() and not target.is_symlink():
                    target.unlink()
                    removed.append(target)
            except Exception:
                # Best-effort: keep going.
                continue
        return removed

    def write(self) -> "Path | None":
        """Persist the manifest. Always safe to call (writes an empty file
        list if nothing was produced).
        """
        if not self._gen_dir:
            return None
        try:
            self._gen_dir.mkdir(parents=True, exist_ok=True)
        except Exception:
            return None
        payload = {
            "version": MANIFEST_VERSION,
            "generated_at": _dt.datetime.now(_dt.timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "files": sorted(self._produced),
        }
        mp = self.manifest_path
        if mp is None:
            return None
        try:
            mp.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
        except Exception:
            return None
        return mp

    # ------------------------------------------------------------------
    # internals
    # ------------------------------------------------------------------

    def _rel(self, path: "Path | str | None") -> "str | None":
        """Return a normalized POSIX relpath under gen_dir, or None if the
        path is outside gen_dir or has an untracked suffix.
        """
        if path is None or self._gen_dir is None:
            return None
        try:
            p = Path(path)
            # ``resolve()`` collapses symlinks/../ and gives us a comparable
            # absolute path; ``strict=False`` because the file may not yet
            # exist (callers sometimes add a path before writing).
            p_abs = p.resolve() if p.is_absolute() else (self._gen_dir / p).resolve()
        except Exception:
            return None
        try:
            rel = p_abs.relative_to(self._gen_dir)
        except ValueError:
            return None
        if p_abs.suffix.lower() not in TRACKED_SUFFIXES:
            return None
        s = rel.as_posix()
        if not s or s == "." or s == MANIFEST_NAME:
            return None
        return s

    def _load_previous(self) -> set[str]:
        mp = self.manifest_path
        if mp is None or not mp.is_file():
            return set()
        try:
            data = json.loads(mp.read_text(encoding="utf-8"))
        except Exception:
            return set()
        if not isinstance(data, dict):
            return set()
        files = data.get("files")
        if not isinstance(files, list):
            return set()
        out: set[str] = set()
        for entry in files:
            if not isinstance(entry, str) or not entry:
                continue
            # Normalize separators and filter by suffix at load time so a
            # tampered manifest can never coerce remove_orphans() into
            # deleting an unexpected file type.
            norm = entry.replace("\\", "/").lstrip("/")
            if Path(norm).suffix.lower() not in TRACKED_SUFFIXES:
                continue
            if norm == MANIFEST_NAME:
                continue
            out.add(norm)
        return out

    def _is_safe_to_remove(self, target: Path) -> bool:
        """Final gate before unlink. Returns True only if the path is a
        tracked-suffix file genuinely located under ``gen_dir``.
        """
        if self._gen_dir is None:
            return False
        try:
            t_abs = target.resolve()
        except Exception:
            return False
        try:
            t_abs.relative_to(self._gen_dir)
        except ValueError:
            return False
        if t_abs == self.manifest_path:
            return False
        if t_abs.suffix.lower() not in TRACKED_SUFFIXES:
            return False
        return True
