"""
core/hitbox_export.py — C header generation for hitbox + sprite props.

Used by:
  - HitboxTab  : individual per-sprite manual export
  - ProjectTab : batch export (All to .c / Scene to .c)
"""

from __future__ import annotations

# Canonical prop groups (order preserved in struct + initialiser)
_PROPS_GROUPS: list[tuple[str, list[str]]] = [
    ("Physics / Movement", [
        "max_speed", "accel", "decel", "weight", "friction",
        "jump_force", "gravity", "max_fall_speed",
        "move_type", "axis_x", "axis_y", "can_jump", "gravity_dir",
    ]),
    ("Combat",             ["hp", "damage", "inv_frames"]),
    ("Misc",               ["score", "anim_spd", "type_id"]),
]

_FIELD_COMMENT: dict[str, str] = {
    "max_speed":      "/* max speed (game units/tick) */",
    "accel":          "/* ticks to reach max_speed (0=instant) */",
    "decel":          "/* deceleration on release (0=instant) */",
    "weight":         "/* mass: 0=light, 255=heavy */",
    "friction":       "/* grip: 0=ice, 255=full */",
    "jump_force":     "/* initial jump velocity; 0=no jump */",
    "gravity":        "/* gravity force (0=none — shmup/topdown) */",
    "max_fall_speed": "/* terminal fall velocity */",
    "move_type":      "/* 0=4-dir, 1=8-dir, 2=side+jump, 3=forced_scroll */",
    "axis_x":         "/* 0=locked, 1=can move on X */",
    "axis_y":         "/* 0=locked, 1=can move on Y */",
    "can_jump":       "/* 0=no jump, 1=jump allowed */",
    "gravity_dir":    "/* 0=down, 1=up, 2=none */",
    "hp":             "/* hit points; 0=invincible */",
    "damage":         "/* damage on contact */",
    "inv_frames":     "/* invincibility frames after hit */",
    "score":          "/* score value x10 on defeat (0..2550 pts) */",
    "anim_spd":       "/* ticks per anim frame (1..60; 0=static) */",
    "type_id":        "/* entity type tag (game-defined) */",
}


def make_hitbox_h(
    name: str,
    src_name: str,
    fw: int,
    fh: int,
    fc: int,
    hitboxes: list[dict],
) -> str:
    """
    Generate the text of `name_hitbox.h`.

    Args:
        name     : C identifier base (stem of the PNG file).
        src_name : display name shown in the header comment.
        fw, fh   : frame width/height in pixels.
        fc       : total number of frames.
        hitboxes : list of {x, y, w, h} dicts (sprite-local coords).
    """
    var = name.replace("-", "_").replace(" ", "_")
    fallback = {"x": -(fw // 2), "y": -(fh // 2), "w": fw, "h": fh}

    lines = [
        f"/* {name}_hitbox.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  {fw}x{fh} px  {fc} frame{'s' if fc != 1 else ''} */",
        "",
        f"#ifndef {name.upper()}_HITBOX_H",
        f"#define {name.upper()}_HITBOX_H",
        "",
        '#include "ngpc_types.h"  /* u8, s8 */',
        "",
        "/* Sprite-local AABB offsets from sprite centre.",
        " * x,y = top-left corner offset (s8: -128..127).",
        " * Distinct from world-space NgpcRect in ngpc_aabb.h (s16 x,y). */",
        "#ifndef NGPC_SPR_HIT_T",
        "#define NGPC_SPR_HIT_T",
        "typedef struct { s8 x; s8 y; u8 w; u8 h; } NgpcSprHit;",
        "#endif",
        "",
        f"static const NgpcSprHit g_{var}_hit[{fc}] = {{",
    ]
    for i in range(fc):
        hb = hitboxes[i] if i < len(hitboxes) else (hitboxes[-1] if hitboxes else fallback)
        enabled = bool(hb.get("enabled", True))
        w = int(hb["w"]) if enabled else 0
        h = int(hb["h"]) if enabled else 0
        comma = "," if i < fc - 1 else " "
        lines.append(
            f"    {{ {int(hb['x']):4d}, {int(hb['y']):4d},"
            f" {w:3d}, {h:3d} }}{comma}"
            f"   /* frame {i} */"
        )
    lines += [
        "};",
        "",
        f"#endif /* {name.upper()}_HITBOX_H */",
        "",
    ]
    return "\n".join(lines)


_PAD_NAMES: list[str] = [
    "PAD_UP", "PAD_DOWN", "PAD_LEFT", "PAD_RIGHT",
    "PAD_A", "PAD_B", "PAD_OPTION",
]

# ctrl dict keys → PAD button for each action (None = unbound)
_CTRL_ACTIONS: list[str] = ["left", "right", "up", "down", "jump", "action", "accel", "brake", "sprint", "shoot"]


def make_ctrl_h(
    name: str,
    src_name: str,
    ctrl: dict,
    props: dict,
    role: str | None = None,
) -> str:
    """
    Generate the text of `name_ctrl.h`.

    The header wraps ngpc_actor (optional module) so main.c needs only:
        NgpcActor hero;
        NAME_CTRL_INIT(hero, start_x, start_y);
        // each frame:
        NAME_CTRL_UPDATE(hero);

    Args:
        name     : C identifier base (stem of the PNG file).
        src_name : display name shown in the header comment.
        ctrl     : {"left": str|None, "right": str|None,
                    "up": str|None, "down": str|None,
                    "jump": str|None, "action": str|None}
        props    : enabled physics props dict (used for INIT macro values).
        role     : gameplay role resolved for this sprite.

    Returns:
        Header text, or empty string if role is not 'player'.
    """
    role = str(role or ctrl.get("role", "none") or "none").strip().lower()
    if role != "player":
        return ""

    var = name.replace("-", "_").replace(" ", "_")
    VAR = var.upper()

    def _pad(key: str) -> str:
        v = ctrl.get(key)
        return v if v else "0"

    # ------------------------------------------------------------------ #
    # Physics values — fall back to sensible defaults if prop not enabled  #
    # ------------------------------------------------------------------ #
    speed        = int(props.get("max_speed",       4))
    sprint_speed = int(props.get("sprint_speed",   8))
    accel        = int(props.get("accel",           8))
    friction     = int(props.get("friction",      200))
    brake_force  = int(props.get("brake_force",    32))
    axis_x       = int(props.get("axis_x",          1))
    axis_y       = int(props.get("axis_y",          1))
    can_jump     = int(props.get("can_jump",         0))
    jump_force   = int(props.get("jump_force",       0))
    gravity      = int(props.get("gravity",          0))
    move_type    = int(props.get("move_type",        0))  # 0=4-dir,1=8-dir,2=platform,3=forced
    shoot_cd     = int(props.get("shoot_cooldown", 10))
    bullet_spd   = int(props.get("bullet_speed",    4))
    bullet_ttl   = int(props.get("bullet_ttl",     60))
    bullet_w     = int(props.get("bullet_w",        4))
    bullet_h     = int(props.get("bullet_h",        4))

    # fx16 conversions:
    #   speed   : integer px/frame → shift left 4  (FX_ONE=16)
    #   accel   : raw fx16 u8 value (0..255), stored directly
    #   friction: raw fx16 u8 value (0..255, e.g. 200 ≈ 12.5/16 ≈ 0.78)
    speed_fx    = f"((fx16){speed} << 4)"
    accel_fx    = f"((fx16){accel})"
    friction_fx = f"((fx16){friction})"

    # Jump velocity in fx16 (negative = upward)
    jump_fx = f"((fx16){jump_force} << 2)"  # ×4 for sub-pixel weight

    btn_left   = _pad("left")
    btn_right  = _pad("right")
    btn_up     = _pad("up")
    btn_down   = _pad("down")
    btn_jump   = _pad("jump")
    btn_action = _pad("action")
    btn_accel  = _pad("accel")
    btn_brake  = _pad("brake")
    btn_sprint = _pad("sprint")
    btn_shoot  = _pad("shoot")

    has_jump = (can_jump or jump_force > 0) and btn_jump != "0"

    # Build dx / dy expressions depending on active axes and move_type
    # move_type 2 (platform): Y axis locked (jump handles vertical)
    effective_axis_y = axis_y and (move_type != 2)

    dx_expr = (
        f"(s8)((ngpc_pad_held & {btn_right} ? 1 : 0)"
        f" - (ngpc_pad_held & {btn_left}  ? 1 : 0))"
        if axis_x and btn_left != "0" and btn_right != "0"
        else "(s8)0"
    )
    dy_expr = (
        f"(s8)((ngpc_pad_held & {btn_down}  ? 1 : 0)"
        f" - (ngpc_pad_held & {btn_up}   ? 1 : 0))"
        if effective_axis_y and btn_up != "0" and btn_down != "0"
        else "(s8)0"
    )

    # move_type description
    move_type_desc = {0: "4-dir", 1: "8-dir", 2: "platform (side+jump)", 3: "forced scroll"}
    move_desc = move_type_desc.get(move_type, str(move_type))
    gravity_desc = f"gravity={gravity}/frame" if gravity else "no gravity"

    lines = [
        f"/* {name}_ctrl.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  role={role}  move={move_desc}  {gravity_desc} */",
        f"/* Requires: optional/ngpc_actor/ + src/core/ngpc_input.h + ngpc_hw.h */",
        "",
        f"#ifndef {VAR}_CTRL_H",
        f"#define {VAR}_CTRL_H",
        "",
        '#include "ngpc_actor/ngpc_actor.h"  /* NgpcActor, ngpc_actor_* */',
        '#include "ngpc_input.h"             /* ngpc_pad_held, ngpc_pad_pressed */',
        '#include "ngpc_hw.h"                /* PAD_UP/DOWN/LEFT/RIGHT/A/B/OPTION */',
        "",
        "/* ================================================================ */",
        "/* BUTTON BINDINGS                                                   */",
        "/* ================================================================ */",
    ]

    for action, pad_val in [
        ("LEFT",   btn_left),
        ("RIGHT",  btn_right),
        ("UP",     btn_up),
        ("DOWN",   btn_down),
        ("JUMP",   btn_jump),
        ("ACTION", btn_action),
        ("ACCEL",  btn_accel),
        ("BRAKE",  btn_brake),
        ("SPRINT", btn_sprint),
        ("SHOOT",  btn_shoot),
    ]:
        lines.append(f"#define {VAR}_BTN_{action:<8} {pad_val}")

    lines += [
        "",
        "/* ================================================================ */",
        "/* PHYSICS CONSTANTS (fx16 fixed-point, FX_ONE = 16)                */",
        "/* ================================================================ */",
        f"#define {VAR}_SPEED     {speed_fx:<24} /* {speed} px/frame max speed */",
        f"#define {VAR}_ACCEL     {accel_fx:<24} /* acceleration (fx16 raw) */",
        f"#define {VAR}_FRICTION  {friction_fx:<24} /* friction factor (fx16 raw) */",
    ]
    if btn_sprint != "0":
        sprint_fx = f"((fx16){sprint_speed} << 4)"
        lines.append(
            f"#define {VAR}_SPRINT_SPEED {sprint_fx:<24} /* {sprint_speed} px/frame sprint speed */"
        )
    if btn_shoot != "0":
        lines += [
            f"#define {VAR}_SHOOT_COOLDOWN {shoot_cd:<22} /* frames between shots */",
            f"#define {VAR}_BULLET_SPEED   ((s8){bullet_spd})<{'':18} /* bullet velocity px/frame */",
            f"#define {VAR}_BULLET_TTL     {bullet_ttl:<22} /* bullet lifetime (frames, 0=OOB only) */",
            f"#define {VAR}_BULLET_W       {bullet_w:<22} /* bullet hitbox width  (px) */",
            f"#define {VAR}_BULLET_H       {bullet_h:<22} /* bullet hitbox height (px) */",
        ]
    if btn_brake != "0":
        lines.append(
            f"#define {VAR}_BRAKE_FORCE ((fx16){brake_force})          /* active braking strength (fx16 raw) */"
        )

    if has_jump:
        lines += [
            f"#define {VAR}_JUMP_FORCE {jump_fx:<24} /* jump impulse (fx16 upward) */",
        ]
    if gravity:
        lines += [
            f"#define {VAR}_GRAVITY   ((fx16){gravity})          /* gravity per frame (fx16 raw) */",
        ]

    lines += [
        "",
        "/* ================================================================ */",
        "/* INIT MACRO — call once at game start                              */",
        f"/* {VAR}_CTRL_INIT(actor, pixel_x, pixel_y)                        */",
        "/* ================================================================ */",
        f"#define {VAR}_CTRL_INIT(actor, sx, sy) \\",
        f"    ngpc_actor_init(&(actor), INT_TO_FX(sx), INT_TO_FX(sy), \\",
        f"        {VAR}_SPEED, {VAR}_ACCEL, {VAR}_FRICTION)",
        "",
        "/* ================================================================ */",
        "/* UPDATE MACRO — call each frame after ngpc_input_update()          */",
        f"/* {VAR}_CTRL_UPDATE(actor)                                         */",
        "/* ================================================================ */",
        f"#define {VAR}_CTRL_UPDATE(actor) do {{ \\",
    ]
    if btn_sprint != "0":
        lines += [
            f"    (actor).speed = ({VAR}_SPRINT_HELD) ? {VAR}_SPRINT_SPEED : {VAR}_SPEED; \\",
        ]
    lines += [
        f"    s8 _dx = {dx_expr}; \\",
        f"    s8 _dy = {dy_expr}; \\",
        f"    ngpc_actor_move(&(actor), _dx, _dy); \\",
    ]

    if has_jump:
        lines += [
            f"    if ((ngpc_pad_pressed & {VAR}_BTN_JUMP) && (actor).vel.y >= 0) {{ \\",
            f"        (actor).vel.y = -{VAR}_JUMP_FORCE; \\",
            f"    }} \\",
        ]

    if gravity:
        lines += [
            f"    (actor).vel.y = FX_ADD((actor).vel.y, {VAR}_GRAVITY); \\",
        ]

    lines += [
        f"    ngpc_actor_update(&(actor)); \\",
        f"}} while(0)",
        "",
    ]

    # Action button helper
    if btn_action != "0":
        lines += [
            "/* ================================================================ */",
            "/* ACTION HELPERS                                                    */",
            "/* ================================================================ */",
            f"#define {VAR}_ACTION_PRESSED  (ngpc_pad_pressed & {VAR}_BTN_ACTION)",
            f"#define {VAR}_ACTION_HELD     (ngpc_pad_held    & {VAR}_BTN_ACTION)",
        ]
    if has_jump:
        lines += [
            f"#define {VAR}_JUMP_PRESSED    (ngpc_pad_pressed & {VAR}_BTN_JUMP)",
        ]
    if btn_accel != "0":
        lines += [
            f"#define {VAR}_ACCEL_HELD      (ngpc_pad_held    & {VAR}_BTN_ACCEL)",
            f"#define {VAR}_ACCEL_PRESSED   (ngpc_pad_pressed & {VAR}_BTN_ACCEL)",
        ]
    if btn_brake != "0":
        lines += [
            f"#define {VAR}_BRAKE_HELD      (ngpc_pad_held    & {VAR}_BTN_BRAKE)",
            f"#define {VAR}_BRAKE_PRESSED   (ngpc_pad_pressed & {VAR}_BTN_BRAKE)",
        ]
    if btn_sprint != "0":
        lines += [
            f"#define {VAR}_SPRINT_HELD     (ngpc_pad_held    & {VAR}_BTN_SPRINT)",
        ]
    if btn_shoot != "0":
        lines += [
            "",
            "/* ================================================================ */",
            "/* SHOOT MACRO — requires ngpc_bullet                               */",
            f"/* {VAR}_SHOOT_UPDATE(actor, pool, tile, pal, shoot_timer)         */",
            f"/* shoot_timer : u8 variable in your game state (cooldown counter) */",
            "/* ================================================================ */",
            '#include "ngpc_bullet/ngpc_bullet.h"  /* NgpcBulletPool, ngpc_bullet_spawn */',
            f"#define {VAR}_SHOOT_PRESSED   (ngpc_pad_pressed & {VAR}_BTN_SHOOT)",
            f"#define {VAR}_SHOOT_UPDATE(actor, pool, tile, pal, shoot_timer) do {{ \\",
            f"    if ((shoot_timer) > 0) --(shoot_timer); \\",
            f"    if ({VAR}_SHOOT_PRESSED && (shoot_timer) == 0) {{ \\",
            f"        s8 _bvx = (actor).dir_x * {VAR}_BULLET_SPEED; \\",
            f"        s8 _bvy = (actor).dir_y * {VAR}_BULLET_SPEED; \\",
            f"        ngpc_bullet_spawn((pool), (actor).pos.x, (actor).pos.y, \\",
            f"            _bvx, _bvy, {VAR}_BULLET_W, {VAR}_BULLET_H, \\",
            f"            (tile), (pal), {VAR}_BULLET_TTL, BULLET_PLAYER); \\",
            f"        (shoot_timer) = {VAR}_SHOOT_COOLDOWN; \\",
            f"    }} \\",
            f"}} while(0)",
        ]

    lines += [
        "",
        "/* ================================================================ */",
        "/* USAGE EXAMPLE                                                     */",
        "/* ================================================================ */",
        "/*",
        f"    NgpcActor {var};",
        f"    {VAR}_CTRL_INIT({var}, 80, 72);   // game_init()",
        f"",
        f"    // game_update() — after ngpc_input_update():",
        f"    {VAR}_CTRL_UPDATE({var});",
        f"    ngpc_sprite_set(0,",
        f"        ngpc_actor_px(&{var}), ngpc_actor_py(&{var}),",
        f"        tile, pal, {var}.dir_x < 0 ? SPR_HFLIP : 0);",
    ]
    if has_jump:
        lines += [
            f"",
            f"    // Optional: clamp fall speed manually:",
            f"    // if ({var}.vel.y > INT_TO_FX({int(props.get('max_fall_speed', 32))})) {{",
            f"    //     {var}.vel.y = INT_TO_FX({int(props.get('max_fall_speed', 32))});",
            f"    // }}",
        ]
    if btn_sprint != "0":
        lines += [
            f"",
            f"    // Sprint — CTRL_UPDATE already adjusts actor.speed automatically.",
        ]
    if btn_shoot != "0":
        lines += [
            f"",
            f"    // Shoot — add in game_update() after CTRL_UPDATE:",
            f"    // static u8 {var}_shoot_cd = 0;",
            f"    // {VAR}_SHOOT_UPDATE({var}, &bullets, BULLET_TILE, BULLET_PAL, {var}_shoot_cd);",
            f"    // ngpc_bullet_update(&bullets);",
        ]
    if btn_accel != "0" or btn_brake != "0":
        lines += [
            f"",
            f"    // Accelerate / Brake — vehicle / top-down racing example:",
            f"    // (manage vel.x manually; HERO_SPEED / HERO_ACCEL / HERO_BRAKE_FORCE are fx16)",
        ]
        if btn_accel != "0":
            lines += [
                f"    // if ({VAR}_ACCEL_HELD) {{",
                f"    //     {var}.vel.x = FX_MIN(FX_ADD({var}.vel.x, {VAR}_ACCEL), {VAR}_SPEED);",
                f"    // }}",
            ]
        if btn_brake != "0":
            lines += [
                f"    // if ({VAR}_BRAKE_HELD) {{",
                f"    //     {var}.vel.x = FX_MAX(FX_SUB({var}.vel.x, {VAR}_BRAKE_FORCE), 0);",
                f"    // }}",
            ]
    lines += [
        "*/",
        "",
        f"#endif /* {VAR}_CTRL_H */",
        "",
    ]
    return "\n".join(lines)


def make_props_h(
    name: str,
    src_name: str,
    fw: int,
    fh: int,
    fc: int,
    props: dict,
) -> str:
    """
    Generate the text of `name_props.h`.

    Args:
        name     : C identifier base.
        src_name : display name shown in the header comment.
        fw, fh   : frame width/height in pixels.
        fc       : total number of frames (info only).
        props    : {prop_key: int_value} for *enabled* props only.

    Returns:
        Header text, or empty string if `props` is empty.
    """
    if not props:
        return ""

    var = name.replace("-", "_").replace(" ", "_")

    # Flatten enabled props in canonical group order
    enabled_ordered: list[tuple[str, int]] = []
    for _grp_label, grp_keys in _PROPS_GROUPS:
        for k in grp_keys:
            if k in props:
                enabled_ordered.append((k, int(props[k])))

    if not enabled_ordered:
        return ""

    enabled_keys = [k for k, _ in enabled_ordered]

    lines = [
        f"/* {name}_props.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  {fw}x{fh} px  {fc} frame{'s' if fc != 1 else ''} */",
        f"/* Active props ({len(enabled_ordered)}): {', '.join(enabled_keys)} */",
        "",
        f"#ifndef {name.upper()}_PROPS_H",
        f"#define {name.upper()}_PROPS_H",
        "",
        '#include "ngpc_types.h"',
        "",
        "typedef struct {",
    ]
    for grp_label, grp_keys in _PROPS_GROUPS:
        grp_active = [k for k in grp_keys if k in props]
        if grp_active:
            lines.append(f"    /* {grp_label} */")
            for k in grp_active:
                decl = f"u8 {k};"
                lines.append(f"    {decl:<18} {_FIELD_COMMENT[k]}")
    lines += [
        "} NgpcSprProps;",
        "",
        f"static const NgpcSprProps g_{var}_props = {{",
    ]
    for i, (k, v) in enumerate(enabled_ordered):
        comma = "," if i < len(enabled_ordered) - 1 else " "
        lines.append(f"    /* {k:<12} */ {v:3d}{comma}")
    lines += [
        "};",
        "",
        f"#endif /* {name.upper()}_PROPS_H */",
        "",
    ]
    return "\n".join(lines)


# Canonical anim state order (for stable #define indices)
ANIM_STATES: list[str] = [
    "idle", "walk", "walk_left", "walk_right", "walk_up", "walk_down",
    "run", "jump", "fall", "land", "attack", "hurt", "death", "special",
]


def make_anims_h(
    name: str,
    src_name: str,
    anims: dict,
) -> str:
    """
    Generate the text of `name_anims.h`.

    Args:
        name     : C identifier base.
        src_name : display name shown in the header comment.
        anims    : {"idle": {"start":0,"count":2,"loop":True,"spd":6}, ...}
                   Only states with keys present in ANIM_STATES are exported.

    Returns:
        Header text, or empty string if anims is empty.
    """
    if not anims:
        return ""

    # Only keep known states, in canonical order
    enabled = [(s, anims[s]) for s in ANIM_STATES if s in anims]
    if not enabled:
        return ""

    var = name.replace("-", "_").replace(" ", "_")
    VAR = var.upper()
    guard = f"{VAR}_ANIMS_H"

    lines = [
        f"/* {name}_anims.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  ({len(enabled)} anim state(s)) */",
        f"/* Usage  : g_{var}_anims[ANIM_xxx].start  (frame index into spritesheet) */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "ngpc_types.h"',
        "",
        "/* Animation state descriptor (4 bytes). */",
        "#ifndef NGPNG_ANIM_T",
        "#define NGPNG_ANIM_T",
        "typedef struct { u8 start; u8 count; u8 loop; u8 spd; } NgpngAnim;",
        "#endif",
        "",
        "/* ---- State index defines ---------------------------------------- */",
    ]

    for i, (state, _) in enumerate(enabled):
        lines.append(f"#define {VAR}_ANIM_{state.upper():<14} {i}u")
    lines.append(f"#define {VAR}_ANIM_COUNT            {len(enabled)}u")
    lines += [
        "",
        "/* ---- Animation table ------------------------------------------- */",
        f"static const NgpngAnim g_{var}_anims[{VAR}_ANIM_COUNT] = {{",
    ]
    for i, (state, data) in enumerate(enabled):
        start = int(data.get("start", 0))
        count = int(data.get("count", 1))
        loop  = 1 if data.get("loop", True) else 0
        spd   = max(1, int(data.get("spd", 6)))
        comma = "," if i < len(enabled) - 1 else " "
        lines.append(f"    {{ {start:3}, {count:3}, {loop}, {spd:2} }}{comma}  /* {state} */")
    lines += [
        "};",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


# ── Motion patterns (ngpc_motion module) ─────────────────────────────────────

_MDIR_MAP: dict[str, str] = {
    "N":  "MDIR_N",  "U":  "MDIR_U",  "D":  "MDIR_D",
    "L":  "MDIR_L",  "R":  "MDIR_R",  "UR": "MDIR_UR",
    "UL": "MDIR_UL", "DR": "MDIR_DR", "DL": "MDIR_DL",
    "*":  "MDIR_ANY",
}
_MBTN_MAP: dict[str, str] = {
    "A": "MBTN_A", "B": "MBTN_B", "OPT": "MBTN_OPT",
}


def _parse_step_token(tok: str) -> tuple[str, bool]:
    """Parse one step token like 'R+A', 'DR', '*+B'.
    Returns (c_expression, valid)."""
    parts = [p.strip() for p in tok.strip().upper().split("+") if p.strip()]
    if not parts:
        return "", False
    dir_c = _MDIR_MAP.get(parts[0])
    if dir_c is None:
        return "", False
    btn_parts: list[str] = []
    for b in parts[1:]:
        bc = _MBTN_MAP.get(b)
        if bc is None:
            return "", False
        btn_parts.append(bc)
    return (f"{dir_c}|{'|'.join(btn_parts)}" if btn_parts else dir_c), True


def _parse_steps_str(steps_str: str) -> tuple[list[str], bool]:
    """Parse a steps string like 'D DR R+A' (spaces or commas).
    Returns (list of C expressions, valid)."""
    tokens = steps_str.strip().replace(",", " ").split()
    if not tokens:
        return [], False
    result: list[str] = []
    for tok in tokens:
        expr, ok = _parse_step_token(tok)
        if not ok:
            return [], False
        result.append(expr)
    return result, True


def make_motion_h(
    name: str,
    src_name: str,
    motion_patterns: list[dict],
    anim_states: list[str],
) -> tuple[str, list[str]]:
    """
    Generate the text of ``name_motion.h``.

    Args:
        name            : C identifier base.
        src_name        : display name for the header comment.
        motion_patterns : list of {name, steps, window, anim} dicts.
        anim_states     : ordered list of *enabled* ANIM_STATES keys for this sprite,
                          used to resolve anim → HERO_ANIM_xxx constants.

    Returns:
        (header_text, errors)
        header_text is "" if no valid patterns could be generated.
        errors is a list of human-readable warning/error strings.
    """
    var = name.replace("-", "_").replace(" ", "_")
    VAR = var.upper()

    valid: list[dict] = []
    errors: list[str] = []

    for i, pat in enumerate(motion_patterns or []):
        pat_name = str(pat.get("name") or "").strip()
        steps_str = str(pat.get("steps") or "").strip()
        anim_raw  = str(pat.get("anim")  or "").strip().lower()
        try:
            window = max(4, min(120, int(pat.get("window") or 20)))
        except (TypeError, ValueError):
            window = 20

        if not pat_name:
            errors.append(f"Pattern {i + 1}: nom manquant — ignoré")
            continue

        c_steps, ok = _parse_steps_str(steps_str)
        if not ok or not c_steps:
            errors.append(
                f"Pattern '{pat_name}': steps invalides ({steps_str!r}) — ignoré\n"
                f"  Notation : N U D L R UR UL DR DL  *=any  +A +B +OPT"
            )
            continue

        # Resolve anim binding — 0xFF if unbound or state not enabled
        anim_expr = "0xFFu"
        if anim_raw:
            if anim_raw in anim_states:
                anim_expr = f"{VAR}_ANIM_{anim_raw.upper()}"
            else:
                errors.append(
                    f"Pattern '{pat_name}': état anim '{anim_raw}' inconnu "
                    f"(pas activé dans Anim States) — dispatch 0xFF"
                )

        safe = pat_name.replace("-", "_").replace(" ", "_").upper()
        valid.append({
            "name":      pat_name,
            "safe":      safe,
            "steps":     c_steps,
            "window":    window,
            "anim_expr": anim_expr,
        })

    if not valid:
        return "", errors

    has_dispatch = any(p["anim_expr"] != "0xFFu" for p in valid)
    guard = f"{VAR}_MOTION_H"

    lines: list[str] = [
        f"/* {var}_motion.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  ({len(valid)} motion pattern(s)) */",
        f"/* Requires: optional/ngpc_motion/ngpc_motion.h */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "ngpc_motion/ngpc_motion.h"',
    ]
    if has_dispatch:
        lines.append(f'#include "{var}_anims.h"   /* {VAR}_ANIM_* constants */')
    lines.append("")

    # Step arrays
    lines.append("/* ── Pattern step arrays (ROM) ─────────────────────────────── */")
    for p in valid:
        arr = ", ".join(p["steps"])
        lines.append(f"static const u8 NGP_FAR _{var}_{p['safe'].lower()}_s[] = {{ {arr} }};")

    # Index #defines
    lines += [
        "",
        "/* ── Pattern index defines ──────────────────────────────────── */",
    ]
    for i, p in enumerate(valid):
        lines.append(f"#define {VAR}_PAT_{p['safe']:<20} {i}u")
    lines.append(f"#define {VAR}_PAT_COUNT                 {len(valid)}u")

    # Pattern table
    lines += [
        "",
        "/* ── Pattern table (ROM) ────────────────────────────────────── */",
        f"static const NgpcMotionPattern NGP_FAR g_{var}_patterns[{VAR}_PAT_COUNT] = {{",
    ]
    for i, p in enumerate(valid):
        arr_name = f"_{var}_{p['safe'].lower()}_s"
        comma = "," if i < len(valid) - 1 else " "
        lines.append(
            f"    {{ {arr_name}, {len(p['steps'])}u, {p['window']}u }}{comma}"
            f"  /* {p['name']} */"
        )
    lines.append("};")

    # Anim dispatch table (only if at least one pattern has a bound anim)
    if has_dispatch:
        lines += [
            "",
            "/* ── Anim dispatch table ────────────────────────────────────── */",
            "/* 0xFF = handle in game code                                     */",
            f"static const u8 NGP_FAR g_{var}_pat_anim[{VAR}_PAT_COUNT] = {{",
        ]
        for i, p in enumerate(valid):
            comma = "," if i < len(valid) - 1 else " "
            lines.append(f"    {p['anim_expr']}{comma}  /* {p['name']} */")
        lines.append("};")

    # Usage comment
    lines += [
        "",
        "/* ── Usage ─────────────────────────────────────────────────── */",
        "/*",
        f"    static NgpcMotionBuf {var}_motion;",
        f"    ngpc_motion_init(&{var}_motion);                    // game_init()",
        "",
        f"    // game_update() — after ngpc_input_update():",
        f"    ngpc_motion_push(&{var}_motion, ngpc_pad_held, ngpc_pad_pressed);",
        f"    u8 pat = ngpc_motion_scan(&{var}_motion, g_{var}_patterns, {VAR}_PAT_COUNT);",
        "    if (pat != 0xFF) {",
        f"        ngpc_motion_clear(&{var}_motion);",
    ]
    if has_dispatch:
        lines += [
            f"        u8 anim = g_{var}_pat_anim[pat];",
            "        if (anim != 0xFF)",
            f"            ngpc_anim_play(&{var}_anim, &g_{var}_anims[anim]);",
            "        // else: handle remaining patterns in game code",
        ]
    else:
        lines += [
            "        // handle all patterns in game code:",
            f"        // switch(pat) {{ case {VAR}_PAT_{valid[0]['safe']}: ... }}",
        ]
    lines += [
        "    }",
        "*/",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines), errors
