"""
core/item_table_gen.py — Generate item_table.h from project item_table.

Project data format (in .ngpcraft):
    {
        "item_table": [
            {"name": "Potion",  "type": "ITEM_HEAL",   "value": 20, "rarity": 0, "price": 5},
            {"name": "Sword +", "type": "ITEM_ATK_UP", "value": 2,  "rarity": 1, "price": 15},
        ]
    }

Generated output (item_table.h):
    #ifndef ITEM_TABLE_GEN_H
    #define ITEM_TABLE_GEN_H
    #define ITEM_HEAL    0u
    ...
    typedef struct { u8 type; u8 value; u8 rarity; u8 price; } NgpcItem;
    #define ITEM_COUNT   2u
    static const NgpcItem g_item_table[ITEM_COUNT] = { ... };
    #endif

Usage:
    from core.item_table_gen import write_item_table_h
    path = write_item_table_h(project_data=data, export_dir=Path("GraphX/gen"))
"""
from __future__ import annotations

import re
from pathlib import Path

_OUTPUT_FILENAME = "item_table.h"


def _sanitize_name(name: str) -> str:
    """Return an UPPER_CASE C identifier from an arbitrary item name."""
    s = re.sub(r"[^a-zA-Z0-9]+", "_", name.strip()).strip("_").upper()
    return s or "UNNAMED"

# Predefined item types — order determines the u8 ID in C
ITEM_TYPES: list[str] = [
    "ITEM_HEAL",
    "ITEM_ATK_UP",
    "ITEM_DEF_UP",
    "ITEM_XP_UP",
    "ITEM_GOLD",
    "ITEM_DICE_PLUS",
    "ITEM_KEY",
    "ITEM_CUSTOM",
]

RARITY_NAMES: list[str] = ["RARITY_COMMON", "RARITY_UNCOMMON", "RARITY_RARE"]

_TYPE_TO_ID: dict[str, int] = {t: i for i, t in enumerate(ITEM_TYPES)}
_RARITY_COUNT = len(RARITY_NAMES)


def make_item_table_h(*, project_data: dict) -> str:
    """Return the full content of item_table.h as a string."""
    data = project_data if isinstance(project_data, dict) else {}
    raw = data.get("item_table", []) or []
    if not isinstance(raw, list):
        raw = []

    items = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        items.append({
            "name":      str(entry.get("name", "") or "").strip() or "item",
            "type":      str(entry.get("type", "ITEM_CUSTOM") or "ITEM_CUSTOM"),
            "value":     max(0, min(255, int(entry.get("value", 0) or 0))),
            "rarity":    max(0, min(_RARITY_COUNT - 1, int(entry.get("rarity", 0) or 0))),
            "price":     max(0, min(255, int(entry.get("price", 0) or 0))),
            "sprite_id": max(0, min(255, int(entry.get("sprite_id", 0) or 0))),
        })

    lines: list[str] = [
        "/* item_table.h — auto-generated by NgpCraft Engine */",
        "/* DO NOT EDIT — re-export from the project tab to update. */",
        "#ifndef ITEM_TABLE_GEN_H",
        "#define ITEM_TABLE_GEN_H",
        "",
        "/* ---- Item type IDs ---- */",
    ]
    for i, t in enumerate(ITEM_TYPES):
        lines.append(f"#define {t:<16} {i}u")

    lines += [
        "",
        "/* ---- Rarity levels ---- */",
    ]
    for i, r in enumerate(RARITY_NAMES):
        lines.append(f"#define {r:<18} {i}u")

    lines += [
        "",
        "typedef struct { u8 type; u8 value; u8 rarity; u8 price; u8 sprite_id; } NgpcItem;",
        "",
    ]

    if not items:
        lines += [
            "#define ITEM_COUNT   0u",
            "/* (no items defined) */",
            "",
            "#endif /* ITEM_TABLE_GEN_H */",
            "",
        ]
        return "\n".join(lines)

    lines.append(f"#define ITEM_COUNT   {len(items)}u")
    lines.append("")

    # Per-item index constants (by sanitised name) — usable in C and trigger resolution
    lines.append("/* ---- Per-item index constants ---- */")
    for i, it in enumerate(items):
        safe = _sanitize_name(it["name"])
        lines.append(f"#define ITEM_IDX_{safe:<24} {i}u  /* {it['name']} */")

    lines.append("")
    lines.append(f"static const NgpcItem g_item_table[ITEM_COUNT] = {{")

    for i, it in enumerate(items):
        sep = "," if i < len(items) - 1 else ""
        rarity_name = RARITY_NAMES[it["rarity"]]
        lines.append(
            f"    /* [{i}] {it['name']:<20} */ "
            f"{{ {it['type']:<16}, {it['value']:>3}u, {rarity_name:<18}, {it['price']:>3}u, {it['sprite_id']:>3}u }}{sep}"
        )

    lines += [
        "};",
        "",
        "#endif /* ITEM_TABLE_GEN_H */",
        "",
    ]
    return "\n".join(lines)


def write_item_table_h(*, project_data: dict, export_dir: Path) -> Path:
    """Write ``item_table.h`` to *export_dir*. Returns the written path."""
    export_dir = Path(export_dir)
    export_dir.mkdir(parents=True, exist_ok=True)
    content = make_item_table_h(project_data=project_data)
    out = export_dir / _OUTPUT_FILENAME
    out.write_text(content, encoding="utf-8")
    return out
