"""
core/sfx_map_gen.py - Generate a small header for gameplay SFX ID mapping.

Goal (AUD-5/AUD-6 support):
- Let the tool store a friendly SFX name list (gameplay IDs) mapped to Sound Creator
  project SFX indices (PROJECT_SFX_* arrays).
- Export a header that the game can include to keep IDs consistent.

Tree-shaking (B3):
  - Scans all triggers across all scenes for action_sfx references.
  - Trailing unused SFX entries are trimmed (no renumbering — IDs stay stable).
  - Mid-array unused entries are kept but annotated with /* unused */.

This intentionally does NOT emit an implementation of Sfx_Play(), because the
template driver defines Sfx_Play unless SFX_PLAY_EXTERNAL is set at build time.
"""

from __future__ import annotations

import re
from pathlib import Path


_RE_IDENT = re.compile(r"[^0-9a-zA-Z_]+")


def _safe_enum_name(name: str) -> str:
    s = (name or "").strip()
    s = _RE_IDENT.sub("_", s)
    s = s.strip("_")
    if not s:
        s = "UNNAMED"
    if s[0].isdigit():
        s = "_" + s
    return "SFX_" + s.upper()


def collect_used_sfx_ids(project_data: dict) -> set[int]:
    """Return the set of gameplay SFX IDs referenced in any trigger's action_sfx."""
    used: set[int] = set()
    if not isinstance(project_data, dict):
        return used
    for scene in project_data.get("scenes", []) or []:
        if not isinstance(scene, dict):
            continue
        for trig in scene.get("triggers", []) or []:
            if not isinstance(trig, dict):
                continue
            if trig.get("action") == "play_sfx":
                sfx = trig.get("action_sfx")
                if sfx is not None:
                    try:
                        used.add(int(sfx))
                    except Exception:
                        pass
    return used


def write_sfx_map_h(*, project_data: dict, export_dir: Path, extra_dirs: list[Path] | None = None) -> Path | None:
    """
    If project_data contains audio.sfx_map, generate:
      export_dir/ngpc_project_sfx_map.h
    and return its path. Otherwise return None.

    Tree-shaking: trailing unused SFX are trimmed. Mid-array unused entries are
    kept (renumbering would break trigger references) but annotated in the header.
    """
    audio = project_data.get("audio", {}) if isinstance(project_data, dict) else {}
    if not isinstance(audio, dict):
        return None
    rows = audio.get("sfx_map", None)
    if not isinstance(rows, list) or not rows:
        return None

    names: list[str] = []
    ids: list[int] = []
    used_enum: set[str] = set()
    for r in rows:
        if not isinstance(r, dict):
            continue
        nm = str(r.get("name") or "").strip()
        pid = r.get("project_id", r.get("id", None))
        try:
            pid_i = int(pid)
        except Exception:
            pid_i = -1

        enum_name = _safe_enum_name(nm)
        base = enum_name
        k = 2
        while enum_name in used_enum:
            enum_name = f"{base}_{k}"
            k += 1
        used_enum.add(enum_name)

        names.append(enum_name)
        ids.append(pid_i)

    if not names:
        return None

    # --- Tree-shaking: find used SFX indices across all triggers ---
    used_sfx = collect_used_sfx_ids(project_data)

    # Trim trailing unused entries (safe — no renumbering of earlier IDs)
    active_count = len(names)
    while active_count > 0 and (active_count - 1) not in used_sfx:
        active_count -= 1
    # If nothing is used, keep at least 1 (so the header isn't empty)
    if active_count == 0 and names:
        active_count = len(names)  # emit all with /* unused */ markers

    names = names[:active_count]
    ids = ids[:active_count]

    out_dirs: list[Path] = [Path(export_dir)]
    if extra_dirs:
        for d in extra_dirs:
            try:
                out_dirs.append(Path(d))
            except Exception:
                pass

    out_h = out_dirs[0] / "ngpc_project_sfx_map.h"

    lines: list[str] = []
    lines.append("/* Auto-generated by NgpCraft Engine -- do not edit */\n")
    lines.append("#ifndef NGPC_PROJECT_SFX_MAP_H\n#define NGPC_PROJECT_SFX_MAP_H\n\n")
    lines.append('#include "ngpc_types.h"  /* u8 */\n\n')
    lines.append(f"#define NGP_GAME_SFX_COUNT {len(names)}u\n\n")
    lines.append("typedef enum NgpGameSfxId {\n")
    for i, nm in enumerate(names):
        suffix = "," if i < (len(names) - 1) else ""
        unused_tag = "  /* unused */" if i not in used_sfx else ""
        lines.append(f"    {nm} = {i}{suffix}{unused_tag}\n")
    lines.append("} NgpGameSfxId;\n\n")
    lines.append("/* Map gameplay SFX ID -> Sound Creator project SFX index.\n")
    lines.append("   Use this table in your Sfx_Play() mapping. */\n")
    lines.append(f"static const u8 g_ngp_game_sfx_to_project_sfx[NGP_GAME_SFX_COUNT] = {{\n")
    for i, pid_i in enumerate(ids):
        v = pid_i if pid_i >= 0 else 0
        suffix = "," if i < (len(ids) - 1) else ""
        unused_tag = "  /* unused */" if i not in used_sfx else ""
        lines.append(f"    (u8){v}{suffix}{unused_tag}\n")
    lines.append("};\n\n")
    lines.append("#endif /* NGPC_PROJECT_SFX_MAP_H */\n")

    for d in out_dirs:
        try:
            d.mkdir(parents=True, exist_ok=True)
            (d / "ngpc_project_sfx_map.h").write_text("".join(lines), encoding="utf-8")
        except Exception:
            pass
    return out_h
