"""
core/sfx_play_autogen.py - Generate an external Sfx_Play() implementation.

Goal (AUD-5 finish):
- When a Sound Creator project is linked (manifest) and a gameplay SFX mapping exists,
  generate a ready-to-compile C file that implements:
      void Sfx_Play(u8 id)
  mapping game IDs -> Sound Creator PROJECT_SFX_* indices.

This file is meant to live next to Sound Creator exports so it can include the
co-generated `ngpc_project_sfx_map.h` locally.
"""

from __future__ import annotations

from pathlib import Path


def write_sfx_play_autogen_c(*, exports_dir: Path) -> Path:
    """
    Write:
      exports_dir/sounds_game_sfx_autogen.c
    """
    exports_dir = Path(exports_dir)
    exports_dir.mkdir(parents=True, exist_ok=True)
    out_c = exports_dir / "sounds_game_sfx_autogen.c"

    lines: list[str] = []
    lines.append("/* Auto-generated by NgpCraft Engine -- do not edit */\n")
    lines.append("/* External Sfx_Play() mapping for Sound Creator project_sfx.c */\n\n")
    lines.append('#include "ngpc_types.h"\n')
    lines.append('#include "sounds.h"\n')
    lines.append('#include "ngpc_project_sfx_map.h"\n\n')

    lines.append("extern const unsigned char PROJECT_SFX_COUNT;\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_ON[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_CH[];\n")
    lines.append("extern const unsigned short PROJECT_SFX_TONE_DIV[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_ATTN[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_FRAMES[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_SW_ON[];\n")
    lines.append("extern const unsigned short PROJECT_SFX_TONE_SW_END[];\n")
    lines.append("extern const signed short PROJECT_SFX_TONE_SW_STEP[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_SW_SPEED[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_SW_PING[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_ENV_ON[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_ENV_STEP[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_TONE_ENV_SPD[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_ON[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_RATE[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_TYPE[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_ATTN[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_FRAMES[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_BURST[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_BURST_DUR[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_ENV_ON[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_ENV_STEP[];\n")
    lines.append("extern const unsigned char PROJECT_SFX_NOISE_ENV_SPD[];\n\n")

    lines.append("void Sfx_Play(u8 id)\n{\n")
    lines.append("    if (id >= (u8)NGP_GAME_SFX_COUNT) return;\n")
    lines.append("    {\n")
    lines.append("        u8 pid = g_ngp_game_sfx_to_project_sfx[id];\n")
    lines.append("        if (pid >= (u8)PROJECT_SFX_COUNT) return;\n")
    lines.append("        if (PROJECT_SFX_TONE_ON[pid]) {\n")
    lines.append("            Sfx_PlayToneEx(\n")
    lines.append("                PROJECT_SFX_TONE_CH[pid], PROJECT_SFX_TONE_DIV[pid], PROJECT_SFX_TONE_ATTN[pid],\n")
    lines.append("                PROJECT_SFX_TONE_FRAMES[pid], PROJECT_SFX_TONE_SW_END[pid], PROJECT_SFX_TONE_SW_STEP[pid],\n")
    lines.append("                PROJECT_SFX_TONE_SW_SPEED[pid], PROJECT_SFX_TONE_SW_PING[pid], PROJECT_SFX_TONE_SW_ON[pid],\n")
    lines.append("                PROJECT_SFX_TONE_ENV_ON[pid], PROJECT_SFX_TONE_ENV_STEP[pid], PROJECT_SFX_TONE_ENV_SPD[pid]\n")
    lines.append("            );\n")
    lines.append("        }\n")
    lines.append("        if (PROJECT_SFX_NOISE_ON[pid]) {\n")
    lines.append("            Sfx_PlayNoiseEx(\n")
    lines.append("                PROJECT_SFX_NOISE_RATE[pid], PROJECT_SFX_NOISE_TYPE[pid], PROJECT_SFX_NOISE_ATTN[pid],\n")
    lines.append("                PROJECT_SFX_NOISE_FRAMES[pid], PROJECT_SFX_NOISE_BURST[pid], PROJECT_SFX_NOISE_BURST_DUR[pid],\n")
    lines.append("                PROJECT_SFX_NOISE_ENV_ON[pid], PROJECT_SFX_NOISE_ENV_STEP[pid], PROJECT_SFX_NOISE_ENV_SPD[pid]\n")
    lines.append("            );\n")
    lines.append("        }\n")
    lines.append("    }\n")
    lines.append("}\n")

    out_c.write_text("".join(lines), encoding="utf-8")
    return out_c

