"""sprite_named_anims_gen.py — Generate NgpcAnimDef arrays for optional/ngpc_anim.

Each named animation produces:
    static const u8  NAME_frames[] = { 0u, 1u, ... };
    static const NgpcAnimDef anim_NAME = ANIM_DEF(NAME_frames, count, speed, ANIM_LOOP);

The output header can be dropped next to the sprite's other headers and included
alongside ngpc_anim.h from the ngpc_anim optional module.
"""

from __future__ import annotations

_MODE_MAP = {"loop": "ANIM_LOOP", "pingpong": "ANIM_PINGPONG", "oneshot": "ANIM_ONESHOT"}


def make_named_anims_h(
    name: str,
    src_name: str,
    named_anims: list[dict],
) -> str:
    """
    Generate the text of ``name_namedanims.h``.

    Args:
        name        : C identifier base (e.g. "player").
        src_name    : display name shown in the header comment.
        named_anims : list of dicts with keys:
                        "name"   (str)       — identifier suffix
                        "frames" (list[int]) — frame indices
                        "speed"  (int)       — NGPC ticks per anim frame (1..255)
                        "mode"   (str)       — "loop" | "pingpong" | "oneshot"

    Returns:
        Header text, or empty string if named_anims is empty or all invalid.
    """
    valid: list[tuple[str, list[int], int, str]] = []
    for entry in named_anims or []:
        anim_name = str(entry.get("name") or "").strip()
        raw_frames = entry.get("frames") or []
        frames = []
        for f in raw_frames:
            try:
                v = int(f)
                if v >= 0:
                    frames.append(v)
            except (TypeError, ValueError):
                pass
        speed = max(1, min(255, int(entry.get("speed") or 6)))
        mode = str(entry.get("mode") or "loop").lower()
        if not anim_name or not frames:
            continue
        if mode not in _MODE_MAP:
            mode = "loop"
        valid.append((anim_name, frames, speed, mode))

    if not valid:
        return ""

    var = name.replace("-", "_").replace(" ", "_")
    VAR = var.upper()
    guard = f"{VAR}_NAMED_ANIMS_H"

    lines = [
        f"/* {var}_namedanims.h -- generated by NgpCraft Engine */",
        f"/* Sprite : {src_name}  ({len(valid)} named animation(s)) */",
        f"/* Requires: optional/ngpc_anim/ngpc_anim.h */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "ngpc_hw.h"',
        '#include "ngpc_anim.h"',
        "",
    ]

    for anim_name, frames, speed, mode in valid:
        safe = anim_name.replace("-", "_").replace(" ", "_")
        arr_name = f"{var}_{safe}_frames"
        def_name = f"anim_{var}_{safe}"
        flag = _MODE_MAP[mode]
        frames_str = ", ".join(f"{f}u" for f in frames)
        lines += [
            f"static const u8 {arr_name}[] = {{ {frames_str} }};",
            f"static const NgpcAnimDef {def_name} = ANIM_DEF({arr_name}, {len(frames)}u, {speed}u, {flag});",
            "",
        ]

    lines += [f"#endif /* {guard} */", ""]
    return "\n".join(lines)
