"""
core/template_updater.py — Download and sync NgpCraft_base_template from GitHub.

Used by the UI "Update Template" button. No git dependency: urllib + zipfile only.
Works both from source and when packaged with PyInstaller (--onedir).

Public API:
    fetch_and_sync(dst, on_progress)  ->  {"added": N, "updated": N, "removed": N}
"""

from __future__ import annotations

import filecmp
import io
import shutil
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path
from typing import Callable

from core.app_paths import user_template_root

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

GITHUB_ZIP = "https://github.com/Tixul/NgpCraft_base_template/archive/refs/heads/main.zip"

_SKIP_DIRS  = {"bin", "build", "__pycache__", ".git", ".vs", ".vscode", "dev", "obj",
               "gen"}          # gen/ = tool-generated output, not part of the template
_SKIP_EXT   = {".pyc", ".rel", ".exe", ".bak"}
_SKIP_FILES = {"main.abs", "main.s24", "main.ngp", "main.ngc",
               "main.map", "main.lst",
               ".gitignore",           # git metadata, irrelevant in the embedded copy
               "roadmap.md",           # internal dev notes
               "ngpng_autorun_main.c"} # generated by PNG Manager at export time


def _template_dst() -> Path:
    """Return the writable template path.

    - Packaged (installer): AppData/Local/NgpCraft Engine/templates/NgpCraft_base_template
      Never touches Program Files — no UAC required.
    - Source / dev: <engine_root>/templates/NgpCraft_base_template
    """
    user = user_template_root()
    if user is not None:
        return user
    return Path(__file__).resolve().parent.parent / "templates" / "NgpCraft_base_template"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _should_skip(name: str, is_dir: bool) -> bool:
    low = name.lower()
    if is_dir:
        return low in _SKIP_DIRS
    if any(low.endswith(e) for e in _SKIP_EXT):
        return True
    if low in _SKIP_FILES:
        return True
    if ".bak" in low:
        return True
    return False


def _files_in(root: Path) -> dict[str, Path]:
    result: dict[str, Path] = {}

    def _walk(d: Path) -> None:
        for item in sorted(d.iterdir()):
            if _should_skip(item.name, item.is_dir()):
                continue
            if item.is_dir():
                _walk(item)
            else:
                result[str(item.relative_to(root))] = item

    _walk(root)
    return result


def _sync(src: Path, dst: Path) -> dict:
    src_files = _files_in(src)
    dst_files = _files_in(dst) if dst.exists() else {}

    added, updated, removed = [], [], []

    for rel, src_path in src_files.items():
        dst_path = dst / rel
        if rel not in dst_files:
            added.append(rel)
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dst_path)
        elif not filecmp.cmp(src_path, dst_path, shallow=False):
            updated.append(rel)
            dst_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_path, dst_path)

    for rel in dst_files:
        if rel not in src_files:
            removed.append(rel)
            (dst / rel).unlink(missing_ok=True)

    # Remove directories that became empty after deletions
    if removed:
        for d in sorted(dst.rglob("*"), reverse=True):
            if d.is_dir():
                try:
                    d.rmdir()
                except OSError:
                    pass

    return {"added": len(added), "updated": len(updated), "removed": len(removed)}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def fetch_and_sync(
    dst: Path | None = None,
    on_progress: Callable[[str], None] | None = None,
) -> dict:
    """
    Download the template zip from GitHub, extract it, and sync it to *dst*.

    Parameters
    ----------
    dst : Path or None
        Destination directory. Defaults to the embedded template inside the tool.
    on_progress : callable(str) or None
        Optional callback called with a human-readable status string at each step.
        Safe to use with Qt signals (emit from a worker thread).

    Returns
    -------
    dict with keys "added", "updated", "removed" (int counts).

    Raises
    ------
    OSError / urllib.error.URLError / zipfile.BadZipFile on failure.
    """
    if dst is None:
        dst = _template_dst()

    def _log(msg: str) -> None:
        if on_progress is not None:
            on_progress(msg)

    _log("Downloading template from GitHub…")
    with urllib.request.urlopen(GITHUB_ZIP, timeout=30) as resp:
        data = resp.read()

    _log("Extracting archive…")
    with tempfile.TemporaryDirectory(prefix="ngpc_update_") as tmp:
        tmp_path = Path(tmp)
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            zf.extractall(tmp_path)

        # GitHub zips contain a single top-level folder: NgpCraft_base_template-main/
        roots = [d for d in tmp_path.iterdir() if d.is_dir()]
        if not roots:
            raise RuntimeError("Archive is empty — nothing to extract.")
        src = roots[0]

        _log("Applying changes…")
        result = _sync(src, dst)

    _log(
        f"Done — {result['added']} added, "
        f"{result['updated']} updated, "
        f"{result['removed']} removed."
    )
    return result
